import numpy as np

#Matrice
#Pour créer une Matrice, on utilise: Matrice=np.array([1,2,3])
print("#Matrice")
print("Pour créer une Matrice, on utilise: Matrice=np.array([1,2,3])")
Matrice=np.array([1,2,3])
print("Matrice=")
print(Matrice)

print("")
print("Création d'une matrice de 1 ligne et 4 colonnes remplis de 1")
Tableau=np.ones((4,))
print("Tableau:",Tableau)

print("")
print("Création d'une matrice de matrice de 1 ligne et 4 colonnes remplis de 1")
Tableau=np.ones((1,4))
print("Tableau:",Tableau)

#.shape
#Pour afficher les dimensions de la Carre, on utilise: Carre.shape
print("")
print("#.shape")
Carre=np.array([[0,1,2],[3,4,5],[6,7,8]])
print("Carre=")
print(Carre)
print("")
print("Pour afficher les dimensions de la Carre, on utilise: Carre.shape",Carre.shape)
print("Carre est une matrice de dimension 2*2")
print("")
Cube=np.array([[[0,1,2],[3,4,5],[6,7,8]],[[9,10,11],[12,13,14],[15,16,17]]])
print("Cube=")
print(Cube)
print("")
print("Dimension de Cube est",Cube.shape)
print("Cube est une matrice de dimension 2*3*3")

#.shape[0]
print("")
print("#.shape[0]")
print("Pour accéder aux taille des dimmension, on utillise: Cube.shape[0]")
print("La taille de la première dimension de Cube est ",Cube.shape[0])
print("La taille de la deuxième dimension de Cube est ",Cube.shape[1])
print("La taille de la troisième dimension de Cube est ",Cube.shape[2])

#.size
#Pour afficher le nombre d'élément dans Carre, on utilise: Carre.size
print("")
print("#.size")
print("Pour afficher le nombre d'élément dans Carre, on utilise: Carre.size",Carre.size)
print("Carre à donc ",Carre.size," élément(s)")
print("Cube à donc ",Cube.size," élément(s)")

#.ndim
#Pour afficher le nombre de dimension dans Carre, on utilise: Carre.ndim
print("")
print("#.ndim")
print("Pour afficher le nombre de dimension dans Carre, on utilise: Carre.ndim",Carre.ndim)
print("Carre à donc ",Carre.ndim," dimension(s)")
print("Cube à donc ",Cube.ndim," dimension(s)")

#np.zeros((,))
#Pour créer une Matrice remplie de zero, on utilise: A=np.zeros((,))
print("")
print("#np.zeros((,))")
print("Pour créer une Matrice remplie de zero, on utilise: A=np.zeros((3,2))")
A=np.zeros((3,2))
print("A=")
print(A)

#np.ones((,))
#Pour créer une Matrice remplie de un, on utilise: A=np.ones((,))
print("")
print("#np.ones((,))")
print("Pour créer une Matrice remplie de un, on utilise: A=np.ones((4,3))")
B=np.ones((4,3))
print("B=")
print(B)

#np.random.randn(,)
#Pour créer une Matrice remplie de nombre aléatoire suivant la distribution normal, on utilise: C=np.random.randn(,)
print("")
print("")
print("Pour créer une Matrice remplie de nombre aléatoire suivant la distribution normal, on utilise: C=np.random.randn(4,2)")
C=np.random.randn(4,2)
print("C=")
print(C)
print("")
print("Réinitialisation de C ")
C=np.random.randn(4,2)
print("Nouveau C=")
print(C)


#np.random.seed()
#Pour fixer les nombres aléatoire on utilise: D=np.random.seed()
print("")
print("#np.random.seed()")
print("Pour fixer les nombres aléatoire on utilise: D=np.random.seed(1)")
D=np.random.seed(1)
D=np.random.randn(4,2)
print("D=")
print(D)
print("")
print("Réinitialisation de D ")
D=np.random.seed(1)
D=np.random.randn(4,2)
print("Nouveau D=")
print(D)

#np.eye()
#Pour créer une Matrice identité, on utilise: E=np.eye()
print("")
print("#np.eye()")
print("Pour créer une Matrice identité, on utilise: E=np.eye(3)")
E=np.eye(3)
print("E=")
print(E)

#np.linspace()
#Pour créer une une ligne avec un nombre de départ, un nombre d'arrivé et le nombre d'élement, on utilise: np.linspace(a,b,c)
#Ou 'a' est le nombre de départ, 'b' est le nombre d'arrivé, et 'c' est le nombre d'élement
print("")
print("#np.linspace()")
print("Pour créer une une ligne avec un nombre de départ, un nombre d'arrivé et le nombre d'élement, on utilise: np.linspace(a,b,c)")
print("Ou 'a' est le nombre de départ, 'b' est le nombre d'arrivé, et 'c' est le nombre d'élement")
print("F=np.linspace(0,10,20)")
F=np.linspace(0,10,20)
print("F=")
print(F)

#np.arange()
#Pour créer une une ligne avec un nombre de départ, un nombre d'arrivé et un pas, on utilise: np.arange(a,b,c)
#Ou 'a' est le nombre de départ, 'b' est le nombre d'arrivé, et 'c' est le pas et c<b
print("")
print("#np.arange()")
print("Pour créer une une ligne avec un nombre de départ, un nombre d'arrivé et un pas, on utilise: np.arange(a,b,c)")
print("Ou 'a' est le nombre de départ, 'b' est le nombre d'arrivé, et 'c' est le pas et c<b")
print("G=np.arange(0,10,20)")
G=np.arange(0,10,0.5)
print("G=")
print(G)

#np.dtype
#Pour contrôler la taille des données dans notre tableau, on utilise: np.dtype=flaot4
print("")
print("#np.dtype")
print("Pour contrôler la taille des données dans notre tableau, on utilise: np.dtype=flaot4")
print("H=np.linspace(0,10,20,dtype=np.float16)")
H=np.linspace(0,10,20,dtype=np.float16)
print("H avec la taille des chiffres sur 16 bits")
print(H)
print("")
print("Nouveaux H")
print("H=np.linspace(0,10,20,dtype=np.float64)")
H=np.linspace(0,10,20,dtype=np.float64)
print("H avec la taille des chiffres sur 64 bits")
print(H)

#np.hstack
#Pour assembler deux tableaux horizontlement, on utilise np.hstack((A,B))
print("")
print("#np.hstack")
print("Pour assembler deux tableaux horizontlement, on utilise np.hstack((A,B))")
print("A=[1,3,5,7,9]")
print("B=[0,2,4,6,8]")
A=np.array([1,3,5,7,9])
B=np.array([0,2,4,6,8])
I=np.hstack((A,B))
print("I=np.hstack((A,B))")
print("I=")
print(I)

#np.vstack
#Pour assembler deux tableaux verticalement, on utilise np.vstack((A,B))
print("")
print("#np.vstack")
print("Pour assembler deux tableaux verticalement, on utilise np.vstack((A,B))")
print("A=[1,3,5,7,9]")
print("B=[0,2,4,6,8]")
A=np.array([1,3,5,7,9])
B=np.array([0,2,4,6,8])
J=np.vstack((A,B))
print("J=np.vstack((A,B))")
print("J=")
print(J)

#np.reshape
#Pour redimensionner une Matrice, on utilise: np.reshape
print("")
print("#np.reshape")
print("Pour redimensionner une Matrice, on utilise: np.reshape")
print("K=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])")
K=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print("K=")
print(K)
print("")
print("Nouveau K=")
print("K=K.reshape(3,4)")
K=K.reshape(3,4)
print(K)

#np.ravel
#Pour redimensionner une Matrice sous forme d'une ligne, on utilise: np.ravel
print("")
print("#np.ravel")
print("Pour redimensionner une Matrice sous forme d'une ligne, on utilise: np.ravel")
print("L=np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])")
L=np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print("L=")
print(L)
print("")
print("Nouveau L=")
print("L=L.ravel()")
L=L.ravel()
print(L)