import asyncio
from dotenv import load_dotenv

from pydantic_ai import Agent

from pydantic_ai.models.openai import OpenAIChatModel
from pydantic_ai.providers.openai import OpenAIProvider

from pydantic_ai.models.ollama import OllamaModel
from pydantic_ai.providers.ollama import OllamaProvider


# Load environment variables from the .env file.
# This is useful for storing configuration values such as API keys.
load_dotenv()


# =========================
# OpenAI configuration
# =========================

# Create an OpenAI model.
# This configuration is commented out because we are using Ollama.
#
# model = OpenAIChatModel(
#     'openai:gpt-4o',
#     provider=OpenAIProvider(openai_client=client),
# )


# =========================
# Ollama configuration
# =========================

# Create an Ollama model running locally.
# "qwen3:1.7b" is the model we want to use.
# The base URL points to the local Ollama API.
model = OllamaModel(
    "qwen3:1.7b",
    provider=OllamaProvider(
        base_url="http://localhost:11434/v1"
    )
)


# Define a tool that can be called by the AI agent.
#
# The tool receives a user's name and returns their favorite color.
# The AI model can decide when this tool is useful and call it
# during the conversation.
def get_favorite(name: str) -> str:
    """Return the favorite color of a user based on their name."""

    # Check if the user is Florian.
    if name == "Florian":
        return "Teal"

    # Check if the user is Mike.
    elif name == "Mike":
        return "Orange"

    # Return a default value when the name is not recognized.
    else:
        return "No information found."


# Create the AI agent.
#
# The "tools" parameter makes the get_favorite() function
# available to the AI model.
#
# The model can decide to call this function when it needs
# information about a user's favorite color.
agent = Agent(
    model,
    system_prompt="You are a helpful assistant.",
    tools=[get_favorite]
)


# Define the asynchronous main function.
async def main():

    # Send a question to the agent.
    #
    # The model should recognize that it needs the user's name
    # and call the get_favorite() tool with "Florian".
    response = await agent.run("What is my favorite color? My name is Florian.")

    # Print the final response generated by the agent.
    print(response.output)


# Run the asynchronous main function when this file
# is executed directly.
if __name__ == "__main__":
    asyncio.run(main())