import datetime as dt
import asyncio
from dotenv import load_dotenv

from pydantic_ai import Agent

from pydantic_ai.models.openai import OpenAIChatModel
from pydantic_ai.providers.openai import OpenAIProvider

from pydantic_ai.models.ollama import OllamaModel
from pydantic_ai.providers.ollama import OllamaProvider

from pydantic_ai.toolsets import FunctionToolset


# =========================
# OpenAI configuration
# =========================

# Create an OpenAI model.
# This configuration is commented out because we are using Ollama.
#
# model = OpenAIChatModel(
#     'openai:gpt-4o',
#     provider=OpenAIProvider(openai_client=client),
# )


# =========================
# Ollama configuration
# =========================

# Create an Ollama model running locally.
# "qwen3:1.7b" is the model we want to use.
# The base URL points to the local Ollama API.
model = OllamaModel(
    "qwen3:1.7b",
    provider=OllamaProvider(
        base_url="http://localhost:11434/v1"
    )
)


# Load environment variables from the .env file.
load_dotenv()


# =========================
# Date and time tools
# =========================

# Return today's date in YYYY-MM-DD format.
#
# Example:
# 2026-09-27
def get_current_date_tool() -> str:

    # Get the current local date and time.
    today = dt.datetime.today()

    # Format the date as YYYY-MM-DD.
    return today.strftime("%Y-%m-%d")


# Return the current weekday name.
#
# Example:
# Sunday
def get_current_weekday_today() -> str:

    # Get the current local date and time.
    today = dt.datetime.today()

    # Return the weekday name.
    return today.strftime("%A")


# Return the current time in HH:MM:SS format.
#
# Example:
# 21:21:42
def get_current_time_tool() -> str:

    # Get the current local date and time.
    now = dt.datetime.now()

    # Format the time as HH:MM:SS.
    return now.strftime("%H:%M:%S")


# =========================
# Create the toolset
# =========================

# Group all date and time functions into a single toolset.
#
# FunctionToolset allows us to organize several Python functions
# that can be used as tools by the AI agent.
datetime_tools = FunctionToolset([
    get_current_date_tool,
    get_current_weekday_today,
    get_current_time_tool
])


# =========================
# Create the agent
# =========================

# Create an AI agent using the selected model.
#
# "toolsets" provides the agent with a collection of tools
# that it can call when needed.
agent = Agent(
    model,
    system_prompt="You are a helpful assistant.",
    toolsets=[datetime_tools],
)


# Define the asynchronous main function.
async def main():

    # Ask the agent for the current date and time.
    #
    # The model can decide which tools it needs to call
    # to answer the user's question.
    response = await agent.run("What is the date and time?")

    # Print the final response generated by the model.
    print(response.output)


# Run the asynchronous main function when this file
# is executed directly.
if __name__ == "__main__":
    asyncio.run(main())
