import sqlite3
from dataclasses import dataclass
import asyncio
from dotenv import load_dotenv

from pydantic_ai import Agent, RunContext

from pydantic_ai.models.openai import OpenAIChatModel
from pydantic_ai.providers.openai import OpenAIProvider

from pydantic_ai.models.ollama import OllamaModel
from pydantic_ai.providers.ollama import OllamaProvider


# =========================
# OpenAI configuration
# =========================

# Create an OpenAI model.
# This configuration is commented out because we are using Ollama.
#
# model = OpenAIChatModel(
#     'openai:gpt-4o',
#     provider=OpenAIProvider(openai_client=client),
# )


# =========================
# Ollama configuration
# =========================

# Create an Ollama model running locally.
# "qwen3:4b" is the model we want to use.
# The base URL points to the local Ollama API.
model = OllamaModel(
    "qwen3:4b",
    provider=OllamaProvider(
        base_url="http://localhost:11434/v1"
    )
)


# Load environment variables from the .env file.
load_dotenv()


# Define the dependencies required by the agent.
#
# A dataclass is used to group all the information
# that the agent and its tools may need during execution.
#
# In this example, the dependencies contain:
# - the user's name
# - a connection to the SQLite database
@dataclass
class MyDependancies:
    user_name: str
    db_connection: sqlite3.Connection


# Create the AI agent.
#
# "deps_type=MyDependancies" tells Pydantic AI
# what type of dependencies will be provided at runtime.
#
# The system prompt defines the general behavior of the assistant.
agent = Agent(
    model,
    deps_type=MyDependancies,
    system_prompt=
        "You are a helpful assistant. "
        "Always start every single message by calling the user by name."
)


# Add a dynamic system prompt.
#
# Unlike a static system_prompt, this function is executed
# at runtime and has access to the current RunContext.
#
# This allows us to dynamically inject the user's name
# into the system prompt.
@agent.system_prompt
def add_user_name(ctx: RunContext[MyDependancies]) -> str:

    # Get the user's name from the dependencies.
    user_name = ctx.deps.user_name

    # Return additional instructions for the model.
    return f"The user name is {user_name}."


# Register a tool that can access the SQLite database.
#
# The RunContext gives the tool access to the dependencies,
# including the database connection.
@agent.tool
def list_all_employees(
    ctx: RunContext[MyDependancies]
) -> list[tuple]:
    """List all employees from the database."""

    # Get the database connection from the dependencies.
    conn = ctx.deps.db_connection

    # Create a cursor to execute SQL queries.
    cursor = conn.cursor()

    # Execute a SQL query to retrieve all employees.
    cursor.execute("SELECT name, age, job FROM person;")

    # Retrieve all rows returned by the query.
    people = cursor.fetchall()

    # Create a list that will contain the employees.
    result = []

    # Convert each database row into a tuple.
    for row in people:
        result.append((row[0], row[1], row[2]))

    # Return the employees to the AI agent.
    return result


# Define the asynchronous main function.
async def main():

    # Open a connection to the SQLite database.
    #
    # "check_same_thread=False" allows the connection
    # to be used from a different thread if necessary.
    db_conn = sqlite3.connect(
        "data/database.db",
        check_same_thread=False
    )


    # Define the current user's name.
    user_name = "Florian"


    # Create the dependencies object.
    #
    # This object will be passed to the agent and made
    # available through RunContext.
    deps = MyDependancies(
        user_name,
        db_conn
    )


    # Run the agent with the dependencies.
    #
    # The model can decide to call list_all_employees()
    # to retrieve the information from the database.
    response = await agent.run(
        "What employees are in DB?",
        deps=deps
    )


    # Print the final response generated by the model.
    print(response.output)


# Run the asynchronous main function when this file
# is executed directly.
if __name__ == "__main__":
    asyncio.run(main())
