from langchain.messages import HumanMessage, SystemMessage
from langchain_ollama import ChatOllama
from langchain.agents import create_agent
from langchain.agents.middleware import ModelRequest, ModelResponse, wrap_model_call
# from langchain.chat_models import init_chat_model


# ============================================================
# 1. MODEL CONFIGURATION
# ============================================================

# Small and fast model used for simple conversations.
BASIC_MODEL = "qwen3.5:0.8b"

# Larger and more capable model used for more complex or longer conversations.
ADVANCED_MODEL = "qwen3.5:9b"


# ============================================================
# 2. INITIALIZE THE LANGUAGE MODELS
# ============================================================

# Initialize the basic model using Ollama.
basic_model = ChatOllama(model=BASIC_MODEL, temperature=0)

# Initialize the advanced model using Ollama.
advanced_model = ChatOllama(model=ADVANCED_MODEL, temperature=0)


# ============================================================
# 3. ALTERNATIVE MODEL CONFIGURATION
# ============================================================

# Another way to initialize a chat model is by using
# LangChain's init_chat_model() function.
#
# This example is commented out because we are currently
# using ChatOllama with local Ollama models.
#
# from langchain.chat_models import init_chat_model
#
# model = init_chat_model(
#     model="gpt-4.1-mini",
#     temperature=0.1
# )


# ============================================================
# 4. DYNAMIC MODEL SELECTION MIDDLEWARE
# ============================================================

@wrap_model_call
def dynamic_model_selection(request: ModelRequest, handler) -> ModelResponse:
    """
    Dynamically select which language model should handle
    the current request.

    The number of messages in the conversation is used
    as a simple criterion for choosing the model.
    """

    # Count the number of messages currently stored
    # in the agent's conversation state.
    message_count = len(request.state["messages"])

    # If the conversation contains more than 3 messages,
    # switch to the more powerful model.
    if message_count > 3:
        model = advanced_model

    # Otherwise, use the smaller and faster model.
    else:
        model = basic_model

    # Override the model used for the current request.
    request = request.override(model=model)

    # Continue the middleware chain with the selected model.
    return handler(request)


# ============================================================
# 5. CREATE THE AGENT
# ============================================================

# Create the agent.
#
# The basic model is used as the default model.
# The middleware can dynamically replace it with the
# advanced model when necessary.
agent = create_agent(
    model=basic_model,
    middleware=[dynamic_model_selection]
)


# ============================================================
# 6. SEND THE CONVERSATION TO THE AGENT
# ============================================================

# Create a small conversation containing:
# - One system message
# - Three user messages
#
# At the beginning of the model call, the middleware
# checks the number of messages and decides which model
# should be used.
response = agent.invoke(
    {
        "messages": [
            SystemMessage(content="You are a helpful assistant."),
            HumanMessage(content="What is 1 + 1 ?"),
            HumanMessage(content="What is 1 + 1 ?"),
            HumanMessage(content="What is 1 + 1 ?"),
        ]
    }
)


# ============================================================
# 7. DISPLAY RAW RESPONSE
# ============================================================

# Print the complete response returned by the agent.
# This can contain all messages exchanged during execution,
# including the final AI response.
print("\n" + 60 * "=")
print("Raw Response:")
print(response)


# ============================================================
# 8. DISPLAY CLEAN RESPONSE
# ============================================================

# Retrieve the last message from the conversation.
# This is normally the final answer generated by the model.
final_message = response["messages"][-1]

print("\nClean Response:")
print(final_message.content)


# ============================================================
# 9. DISPLAY THE MODEL USED
# ============================================================

# The response metadata contains information about
# the model that generated the final response.
#
# This is useful for verifying whether the middleware
# selected the basic or advanced model.
print("\nModel used:")
print(final_message.response_metadata["model_name"])