# from langchain.chat_models import init_chat_model
from langchain_ollama import ChatOllama
from base64 import b64encode


# ============================================================
# 1. MODEL CONFIGURATION
# ============================================================

# Name of the model installed and available in Ollama.
MODEL = "qwen3.5:9b"


# ============================================================
# 2. INITIALIZE THE CHAT MODEL
# ============================================================

# Create a ChatOllama instance.
# This object is used to send messages to the local
# language model through Ollama.
model = ChatOllama(
    model=MODEL,

    # A temperature of 0 makes the model's responses
    # more deterministic and less random.
    temperature=0
)


# ============================================================
# 3. ALTERNATIVE MODEL CONFIGURATION
# ============================================================

# Another option is to use LangChain's init_chat_model().
#
# This example is commented out because we are currently
# using ChatOllama with a local model.
#
# model = init_chat_model(
#     model="gpt-4.1-mini",
#     temperature=0.1
# )



# ============================================================
# 4. CREATE THE USER MESSAGE
# ============================================================

# url = 'https://neuralnine.com/wp-content/uploads/2025/04/neuralnine_logo_transparent-1024x493.png'

# Create a multimodal message containing:
# - A text instruction
# - An image encoded in Base64
#
# The image is provided together with its MIME type so that
# the model knows which image format it is receiving.

message = {
    'role': 'user',
    'content': [
        {'type': 'text', 'text': 'Describe the contents of this image.'},
        {
            'type': 'image',
            'base64': b64encode(open('logo.png', 'rb').read()).decode(),
            'mime_type': 'image/png'
        }
        ]
}


# ============================================================
# 5. SEND THE MESSAGE TO THE MODEL
# ============================================================

# Send the multimodal message to the Ollama model.
# The model will analyze both the text instruction
# and the provided image.
response = model.invoke([message])


# ============================================================
# 6. DISPLAY THE MODEL RESPONSE
# ============================================================

# Print the text generated by the vision-language model.
print("\n" + 60 * "=")
print("Response:")
print(response.content)