from langchain_ollama import ChatOllama
from langchain.agents import create_agent
from langchain.agents.middleware import SummarizationMiddleware
from langchain.messages import HumanMessage, SystemMessage
# from langchain.chat_models import init_chat_model


# ============================================================
# 1. MODEL CONFIGURATION
# ============================================================

# Name of the model installed and available in Ollama.
MODEL = "qwen3.5:9b"


# ============================================================
# 2. INITIALIZE THE CHAT MODEL
# ============================================================

# Create a ChatOllama instance.
# This object is used to communicate with the local
# language model through Ollama.
model = ChatOllama(
    model=MODEL,

    # A temperature of 0 makes the model's responses
    # more deterministic and less random.
    temperature=0
)


# ============================================================
# 3. ALTERNATIVE MODEL CONFIGURATION
# ============================================================

# Another option is to use LangChain's init_chat_model().
#
# This example is commented out because we are currently
# using ChatOllama with a local Ollama model.
#
# model = init_chat_model(
#     model="gpt-4.1-mini",
#     temperature=0.1
# )


# ============================================================
# 4. CREATE THE AGENT WITH SUMMARIZATION
# ============================================================

# SummarizationMiddleware automatically summarizes the
# conversation when it becomes too long.
# Create the agent and attach the summarization middleware.
# The middleware monitors the conversation length and
# automatically summarizes older messages once the
# configured token threshold is reached.

agent = create_agent(
    model=model,
    middleware=[
        SummarizationMiddleware(

            # Model used to generate the conversation summary.
            model=model,

            # Trigger summarization when the conversation
            # reaches approximately 4000 tokens.
            trigger=("tokens", 4000),

            # Keep the 20 most recent messages after
            # the conversation has been summarized.
            message_to_keep=20,

            # Instructions given to the model when generating
            # the conversation summary.
            summary_prompt=(
                "Summarize the most important key points "
                "that are relevant for the conversation."
            )
        )
    ]
)


# ============================================================
# 5. INVOKE THE AGENT
# ============================================================

# Send a question to the agent.
response = agent.invoke(
    {
        "messages": [
            SystemMessage(content="You are a helpful assistant."),
            HumanMessage(content="What is PCA?")
        ]
    }
)


# ============================================================
# 6. DISPLAY RAW RESPONSE
# ============================================================

# Print the complete response returned by the agent.
# This can contain all messages exchanged during execution,
# including any summarized conversation state.
print("\n" + 60 * "=")
print("Raw Response:")
print(response)


# ============================================================
# 7. DISPLAY CLEAN RESPONSE
# ============================================================

# Retrieve the last message from the conversation.
# This is normally the final answer generated by the model.
final_message = response["messages"][-1]

print("\nClean Response:")
print(final_message.content)