import requests

# from langchain.chat_models import init_chat_model
from langchain_ollama import ChatOllama
from langchain.messages import HumanMessage, AIMessage, SystemMessage


# ============================================================
# 1. MODEL CONFIGURATION
# ============================================================

# Name of the model installed and available in Ollama.
MODEL = "qwen3.5:9b"

# Create a ChatOllama instance.
# This object is used to send messages to the local
# language model through Ollama.

model = ChatOllama(
    model=MODEL,

    # A temperature of 0 makes the model's responses
    # more deterministic and less creative/random.
    temperature=0
)


# ============================================================
# 2. ALTERNATIVE MODEL CONFIGURATION
# ============================================================

# Another option is to use LangChain's init_chat_model().
#
# This example is commented out because we are currently
# using ChatOllama with a local model.
#
# model = init_chat_model(
#     model='gpt-4.1-mini',
#     temperature=0.1
# )


# ============================================================
# 3. BUILD THE CONVERSATION
# ============================================================

# Import the different message types used to build a conversation.
# SystemMessage  -> Defines the behavior and role of the AI.
# HumanMessage   -> Represents a message sent by the user.
# AIMessage      -> Represents a previous response generated by the AI.

# A conversation is represented as a list of messages.
# The order of these messages is important because
# the model uses them as conversation history.

conversation = [

    SystemMessage("You are a helpful assistant for questions regarding programming"),
    HumanMessage("What is Python?"),
    AIMessage("Python is an interpreted programming language."),
    HumanMessage("When was it released?"),
]


# ============================================================
# 4. SEND THE CONVERSATION TO THE MODEL
# ============================================================

# invoke() sends the entire conversation to the model.
#
# The model receives:
#
# 1. The system instructions
# 2. The first user question
# 3. The previous AI answer
# 4. The user's follow-up question
#
# The model can therefore use the previous messages
# as context when generating its answer.
response = model.invoke(conversation)


# ============================================================
# 5. DISPLAY THE RAW RESPONSE
# ============================================================

# Print the complete response object returned by LangChain.
# This object contains more than just the model's text.
# It can also contain metadata, response information,
# and other details about the generated message.

print("\n" + 60 * "=")
print("Raw Response:")
print(response)


# ============================================================
# 6. DISPLAY ONLY THE MODEL'S TEXT
# ============================================================

# The response object contains a "content" attribute.
# response.content gives us only the text generated
# by the language model, without the additional metadata.

print("\nClean Response:")
print(response.content)
